/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlchemyPay: typeof import('./src/components/AlchemyPay/index.vue')['default']
    AttributeItem: typeof import('./src/components/EquipmentInfo/AttributeItem.vue')['default']
    Attributes: typeof import('./src/components/EquipmentInfo/Attributes.vue')['default']
    Button: typeof import('./src/components/Button/index.vue')['default']
    CopyButton: typeof import('./src/components/CopyButton/index.vue')['default']
    EquipmentInfo: typeof import('./src/components/EquipmentInfo/index.vue')['default']
    GoogleLogin: typeof import('./src/components/GoogleLogin/index.vue')['default']
    InstallPWA: typeof import('./src/components/InstallPWA/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    LolProgressBar: typeof import('./src/components/EquipmentInfo/LolProgressBar.vue')['default']
    MergeEqpt: typeof import('./src/components/MergeEqpt/index.vue')['default']
    MergeEqptResult: typeof import('./src/components/MergeEqptResult/index.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    ModalContainer: typeof import('./src/components/ModalContainer/index.vue')['default']
    Navbar: typeof import('./src/components/Navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareInsModal: typeof import('./src/components/ShareModal/ShareInsModal.vue')['default']
    ShareModal: typeof import('./src/components/ShareModal/index.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar/index.vue')['default']
    Toast: typeof import('./src/components/Toast/Toast.vue')['default']
  }
}
